sudo: required

language: php

php:
  - 5.6
  - 7.0
  - 7.2
  - nightly

services:
  - docker

before_install:
  - docker run -d --name="teamspeak_server" -p "9987:9987/udp" -p 10011:10011 -p 30033:30033 teamspeak:latest
  - docker ps -a
  - docker logs teamspeak_server

before_script:
  - composer install