TeamSpeak 3 PHP Framework: TeamSpeak3_Adapter_ServerQuery_Event Class Reference
TeamSpeak3_Adapter_ServerQuery_Event Class Reference
Provides methods to analyze and format a ServerQuery event.
Public Member Functions
__construct (TeamSpeak3_Helper_String $evt, TeamSpeak3_Node_Host $con=null)
Creates a new TeamSpeak3_Adapter_ServerQuery_Event object.
getType ()
Returns the event type string.
getData ()
Returns the event data array.
getMessage ()
Returns the event data as an unparsed string.
offsetExists ($offset)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetUnset ($offset)
__get ($offset)
__set ($offset, $value)
Protected Attributes
$type = null
$data = null
$mesg = null
Detailed Description
Provides methods to analyze and format a ServerQuery event.
Definition at line 32 of file Event.php.
Constructor & Destructor Documentation
TeamSpeak3_Adapter_ServerQuery_Event::__construct (TeamSpeak3_Helper_String $evt, TeamSpeak3_Node_Host $con = null)
Creates a new TeamSpeak3_Adapter_ServerQuery_Event object.
Parameters
TeamSpeak3_Helper_String $evt
TeamSpeak3_Node_Host $con
Exceptions
TeamSpeak3_Adapter_Exception
Returns
TeamSpeak3_Adapter_ServerQuery_Event
Definition at line 63 of file Event.php.
References TeamSpeak3\ERROR, TeamSpeak3\EVENT, TeamSpeak3_Helper_Signal\getInstance(), TeamSpeak3\SEPARATOR_CELL, TeamSpeak3\SEPARATOR_PAIR, TeamSpeak3_Helper_String\split(), and TeamSpeak3_Helper_String\startsWith().
   {
     if(!$evt->startsWith(TeamSpeak3::EVENT))
     {
       throw new TeamSpeak3_Adapter_Exception("invalid notification event format");
     }
     list($type, $data) = $evt->split(TeamSpeak3::SEPARATOR_CELL, 2);
     if(empty($data))
     {
       throw new TeamSpeak3_Adapter_Exception("invalid notification event data");
     }
     $fake = new TeamSpeak3_Helper_String(TeamSpeak3::ERROR . TeamSpeak3::SEPARATOR_CELL . "id" . TeamSpeak3::SEPARATOR_PAIR . 0 . TeamSpeak3::SEPARATOR_CELL . "msg" . TeamSpeak3::SEPARATOR_PAIR . "ok");
     $repl = new TeamSpeak3_Adapter_ServerQuery_Reply(array($data, $fake), $type);
     $this->type = $type->substr(strlen(TeamSpeak3::EVENT));
     $this->data = $repl->toList();
     $this->mesg = $data;
     TeamSpeak3_Helper_Signal::getInstance()->emit("notifyEvent", $this, $con);
     TeamSpeak3_Helper_Signal::getInstance()->emit("notify" . ucfirst($this->type), $this, $con);
   }
Member Function Documentation
TeamSpeak3_Adapter_ServerQuery_Event::getType ()
Returns the event type string.
Returns
TeamSpeak3_Helper_String
Definition at line 93 of file Event.php.
Referenced by offsetSet().
   {
     return $this->type;
   }
TeamSpeak3_Adapter_ServerQuery_Event::getData ()
Returns the event data array.
Returns
array
Definition at line 103 of file Event.php.
   {
     return $this->data;
   }
TeamSpeak3_Adapter_ServerQuery_Event::getMessage ()
Returns the event data as an unparsed string.
Returns
TeamSpeak3_Helper_String
Definition at line 113 of file Event.php.
   {
     return $this->mesg;
   }
TeamSpeak3_Adapter_ServerQuery_Event::offsetExists ($offset)
Definition at line 121 of file Event.php.
Referenced by offsetGet().
   {
     return array_key_exists($offset, $this->data) ? TRUE : FALSE;
   }
TeamSpeak3_Adapter_ServerQuery_Event::offsetGet ($offset)
Definition at line 129 of file Event.php.
References offsetExists().
Referenced by __get().
   {
     if(!$this->offsetExists($offset))
     {
       throw new TeamSpeak3_Adapter_ServerQuery_Exception("invalid parameter", 0x602);
     }
     return $this->data[$offset];
   }
TeamSpeak3_Adapter_ServerQuery_Event::offsetSet ($offset, $value)
Definition at line 142 of file Event.php.
References getType().
Referenced by __set().
   {
     throw new TeamSpeak3_Node_Exception("event '" . $this->getType() . "' is read only");
   }
TeamSpeak3_Adapter_ServerQuery_Event::offsetUnset ($offset)
Definition at line 150 of file Event.php.
   {
     unset($this->data[$offset]);
   }
TeamSpeak3_Adapter_ServerQuery_Event::__get ($offset)
Definition at line 158 of file Event.php.
References offsetGet().
   {
     return $this->offsetGet($offset);
   }
TeamSpeak3_Adapter_ServerQuery_Event::__set ($offset, $value)
Definition at line 166 of file Event.php.
References offsetSet().
   {
     $this->offsetSet($offset, $value);
   }
The documentation for this class was generated from the following file:
TeamSpeak3/Adapter/ServerQuery/Event.php