TeamSpeak 3 PHP Framework: TeamSpeak3_Adapter_TSDNS Class Reference
TeamSpeak3_Adapter_TSDNS Class Reference
Provides methods to query a TSDNS server.
Public Member Functions
syn ()
Connects the TeamSpeak3_Transport_Abstract object and performs initial actions on the remote server.
__destruct ()
The TeamSpeak3_Adapter_FileTransfer destructor.
resolve ($tsdns)
Queries the TSDNS server for a specified virtual hostname and returns the result.
__sleep ()
Commit pending data.
__wakeup ()
Reconnects to the remote server.
getProfiler ()
Returns the profiler timer used for this connection adapter.
getTransport ()
Returns the transport object used for this connection adapter.
getTransportHost ()
Returns the hostname or IPv4 address the underlying TeamSpeak3_Transport_Abstract object is connected to.
getTransportPort ()
Returns the port number of the server the underlying TeamSpeak3_Transport_Abstract object is connected to.
Protected Member Functions
initTransport ($options, $transport="TeamSpeak3_Transport_TCP")
Loads the transport object object used for the connection adapter and passes a given set of options.
Protected Attributes
$default_port = 41144
$options = null
$transport = null
Detailed Description
Provides methods to query a TSDNS server.
Definition at line 32 of file TSDNS.php.
Constructor & Destructor Documentation
TeamSpeak3_Adapter_TSDNS::__destruct ()
The TeamSpeak3_Adapter_FileTransfer destructor.
Returns
void
Definition at line 65 of file TSDNS.php.
References TeamSpeak3_Adapter_Abstract\getTransport().
   {
     if($this->getTransport() instanceof TeamSpeak3_Transport_Abstract && $this->getTransport()->isConnected())
     {
       $this->getTransport()->disconnect();
     }
   }
Member Function Documentation
TeamSpeak3_Adapter_TSDNS::syn ()
Connects the TeamSpeak3_Transport_Abstract object and performs initial actions on the remote server.
Exceptions
TeamSpeak3_Adapter_Exception
Returns
void
Definition at line 48 of file TSDNS.php.
References TeamSpeak3_Helper_Signal\getInstance(), TeamSpeak3_Helper_Profiler\init(), and TeamSpeak3_Adapter_Abstract\initTransport().
   {
     if(!isset($this->options["port"]) || empty($this->options["port"])) $this->options["port"] = $this->default_port;
     $this->initTransport($this->options);
     $this->transport->setAdapter($this);
     TeamSpeak3_Helper_Profiler::init(spl_object_hash($this));
     TeamSpeak3_Helper_Signal::getInstance()->emit("tsdnsConnected", $this);
   }
TeamSpeak3_Adapter_TSDNS::resolve ($tsdns)
Queries the TSDNS server for a specified virtual hostname and returns the result.
Parameters
string $tsdns
Exceptions
TeamSpeak3_Adapter_TSDNS_Exception
Returns
TeamSpeak3_Helper_String
Definition at line 80 of file TSDNS.php.
References TeamSpeak3_Helper_Signal\getInstance(), and TeamSpeak3_Adapter_Abstract\getTransport().
   {
     $this->getTransport()->sendLine($tsdns);
     $repl = $this->getTransport()->readLine();
     $this->getTransport()->disconnect();
     if($repl->section(":", 0)->toInt() == 404)
     {
       throw new TeamSpeak3_Adapter_TSDNS_Exception("unable to resolve TSDNS hostname (" . $tsdns . ")");
     }
     TeamSpeak3_Helper_Signal::getInstance()->emit("tsdnsResolved", $tsdns, $repl);
     return $repl;
   }
TeamSpeak3_Adapter_Abstract::__sleep () inherited
Commit pending data.
Returns
array
Definition at line 85 of file Abstract.php.
   {
     return array("options");
   }
TeamSpeak3_Adapter_Abstract::__wakeup () inherited
Reconnects to the remote server.
Returns
void
Definition at line 95 of file Abstract.php.
References TeamSpeak3_Adapter_Abstract\syn().
   {
     $this->syn();
   }
TeamSpeak3_Adapter_Abstract::getProfiler () inherited
Returns the profiler timer used for this connection adapter.
Returns
TeamSpeak3_Helper_Profiler_Timer
Definition at line 105 of file Abstract.php.
References TeamSpeak3_Helper_Profiler\get().
Referenced by TeamSpeak3_Adapter_FileTransfer\download(), TeamSpeak3_Adapter_ServerQuery\getQueryRuntime(), TeamSpeak3_Adapter_FileTransfer\init(), TeamSpeak3_Adapter_ServerQuery\request(), and TeamSpeak3_Adapter_FileTransfer\upload().
   {
     return TeamSpeak3_Helper_Profiler::get(spl_object_hash($this));
   }
TeamSpeak3_Adapter_Abstract::getTransport () inherited
Returns the transport object used for this connection adapter.
Returns
TeamSpeak3_Transport_Abstract
Definition at line 115 of file Abstract.php.
Referenced by TeamSpeak3_Adapter_FileTransfer\__destruct(), __destruct(), TeamSpeak3_Adapter_Blacklist\__destruct(), TeamSpeak3_Adapter_ServerQuery\__destruct(), TeamSpeak3_Adapter_Update\__destruct(), TeamSpeak3_Adapter_FileTransfer\download(), TeamSpeak3_Adapter_Abstract\getTransportHost(), TeamSpeak3_Adapter_Abstract\getTransportPort(), TeamSpeak3_Adapter_FileTransfer\init(), TeamSpeak3_Adapter_Blacklist\isBlacklisted(), TeamSpeak3_Adapter_FileTransfer\passthru(), TeamSpeak3_Adapter_ServerQuery\request(), resolve(), TeamSpeak3_Adapter_ServerQuery\syn(), TeamSpeak3_Adapter_Update\syn(), TeamSpeak3_Adapter_FileTransfer\upload(), and TeamSpeak3_Adapter_ServerQuery\wait().
   {
     return $this->transport;
   }
TeamSpeak3_Adapter_Abstract::initTransport ($options, $transport = "TeamSpeak3_Transport_TCP") protected inherited
Loads the transport object object used for the connection adapter and passes a given set of options.
Parameters
array $options
string $transport
Exceptions
TeamSpeak3_Adapter_Exception
Returns
void
Definition at line 129 of file Abstract.php.
Referenced by TeamSpeak3_Adapter_FileTransfer\syn(), syn(), TeamSpeak3_Adapter_Blacklist\syn(), TeamSpeak3_Adapter_ServerQuery\syn(), and TeamSpeak3_Adapter_Update\syn().
   {
     if(!is_array($options))
     {
       throw new TeamSpeak3_Adapter_Exception("transport parameters must provided in an array");
     }
     $this->transport = new $transport($options);
   }
TeamSpeak3_Adapter_Abstract::getTransportHost () inherited
Returns the hostname or IPv4 address the underlying TeamSpeak3_Transport_Abstract object is connected to.
Returns
string
Definition at line 145 of file Abstract.php.
References TeamSpeak3_Adapter_Abstract\getTransport().
   {
     return $this->getTransport()->getConfig("host", "0.0.0.0");
   }
TeamSpeak3_Adapter_Abstract::getTransportPort () inherited
Returns the port number of the server the underlying TeamSpeak3_Transport_Abstract object is connected to.
Returns
string
Definition at line 156 of file Abstract.php.
References TeamSpeak3_Adapter_Abstract\getTransport().
   {
     return $this->getTransport()->getConfig("port", "0");
   }
The documentation for this class was generated from the following file:
TeamSpeak3/Adapter/TSDNS.php