TeamSpeak 3 PHP Framework: TeamSpeak3_Helper_Profiler Class Reference
TeamSpeak3_Helper_Profiler Class Reference
Helper class for profiler handling.
Static Public Member Functions
static init ($name="default")
Inits a timer.
static start ($name="default")
Starts a timer.
static stop ($name="default")
Stops a timer.
static get ($name="default")
Returns a timer.
Static Protected Attributes
static $timers = array()
Detailed Description
Helper class for profiler handling.
Definition at line 32 of file Profiler.php.
Member Function Documentation
static TeamSpeak3_Helper_Profiler::init ($name = "default") static
Inits a timer.
Parameters
string $name
Returns
void
Definition at line 47 of file Profiler.php.
Referenced by TeamSpeak3_Adapter_FileTransfer\syn(), TeamSpeak3_Adapter_TSDNS\syn(), TeamSpeak3_Adapter_Blacklist\syn(), TeamSpeak3_Adapter_ServerQuery\syn(), and TeamSpeak3_Adapter_Update\syn().
   {
     self::$timers[$name] = new TeamSpeak3_Helper_Profiler_Timer($name);
   }
static TeamSpeak3_Helper_Profiler::start ($name = "default") static
Starts a timer.
Parameters
string $name
Returns
void
Definition at line 58 of file Profiler.php.
Referenced by TeamSpeak3\init().
   {
     if(array_key_exists($name, self::$timers))
     {
       self::$timers[$name]->start();
     }
     else
     {
       self::$timers[$name] = new TeamSpeak3_Helper_Profiler_Timer($name);
     }
   }
static TeamSpeak3_Helper_Profiler::stop ($name = "default") static
Stops a timer.
Parameters
string $name
Returns
void
Definition at line 76 of file Profiler.php.
   {
     if(!array_key_exists($name, self::$timers))
     {
       self::init($name);
     }
     self::$timers[$name]->stop();
   }
static TeamSpeak3_Helper_Profiler::get ($name = "default") static
Returns a timer.
Parameters
string $name
Returns
TeamSpeak3_Helper_Profiler_Timer
Definition at line 92 of file Profiler.php.
Referenced by TeamSpeak3_Adapter_Abstract\getProfiler().
   {
     if(!array_key_exists($name, self::$timers))
     {
       self::init($name);
     }
     return self::$timers[$name];
   }
The documentation for this class was generated from the following file:
TeamSpeak3/Helper/Profiler.php